[project]
name = "child-screen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "kagglehub[pandas-datasets]>=0.3.10",
    "marimo>=0.11.30",
]
